"""VibeOCR HTTP v2 protocol: stable DTOs, error codes and schema parser.

This package is the single source of truth for the supervisor ↔ frontend
contract. It is dependency-free (stdlib only) so Runtime Client, Backend and
both frontends can consume it without creating a cycle.

Design rules (see ``docs/protocol-v2-design.md`` in the repository):

* DTOs only carry JSON-native types or lists/dicts of JSON-native types plus
  ``enum.Enum``/``datetime``/``uuid.UUID`` helpers exposed as ISO strings.
* ``schema_version`` is always present on the wire (currently 2).
* Request parsers reject unknown fields, illegal state transitions and unknown
  error codes; response readers retain unknown optional fields.
"""

from __future__ import annotations

from .dtos import (
    TERMINAL_ITEM_STATES,
    TERMINAL_JOB_STATES,
    CancelMode,
    EvictionReason,
    ItemOutcome,
    ItemState,
    JobCommand,
    JobCommandKind,
    JobItem,
    JobKind,
    JobPriority,
    JobRef,
    JobSnapshot,
    JobState,
    JobSummary,
    JobUpdate,
    PipelineSelection,
    PipelineSpec,
    ProgressSnapshot,
    ProgressUnit,
    RecognitionResourceKind,
    ResidencyEntry,
    ResidencyKind,
    ResidencyStatus,
    ResultEntry,
    RuntimeAccelerator,
    RuntimeComponentActualState,
    RuntimeComponentDesiredState,
    RuntimeComponentState,
    RuntimeComponentStatus,
    RuntimeDriftReason,
    RuntimeMaintenanceCommand,
    RuntimeMaintenanceCommandKind,
    RuntimeMaintenanceEvent,
    RuntimeMaintenanceEventType,
    RuntimeMaintenanceOperation,
    RuntimeMaintenancePhase,
    RuntimeMaintenanceReceipt,
    RuntimeMaintenanceRequest,
    RuntimeMaintenanceStatus,
    RuntimeMaintenanceUpdate,
    RuntimeOperationState,
    RuntimeProfileStatus,
    RuntimeServiceState,
    RuntimeSourceIdentity,
    RuntimeStatusSnapshot,
    SettingsSnapshot,
    StageEvent,
    SubmitItem,
    SubmitRequest,
    UnknownJobError,
    new_job_id,
)
from .errors import (
    ErrorCategories,
    ErrorCode,
    ErrorPayload,
    error_registry,
    load_error_registry,
)
from .ocr import (
    OCR_RESULT_PAYLOAD_TYPE,
    OcrResultV1,
    OcrTextBlockV1,
    parse_ocr_result_payload,
)
from .parser import (
    ContractError,
    JobStateTransitionError,
    SchemaValidator,
    assert_item_transition,
    assert_job_transition,
    is_terminal_item,
    is_terminal_job,
    parse_error_payload,
    parse_job_command,
    parse_job_ref,
    parse_job_snapshot,
    parse_job_update,
    parse_pipeline_selection,
    parse_pipeline_spec,
    parse_residency_entry,
    parse_runtime_maintenance_event,
    parse_runtime_maintenance_receipt,
    parse_runtime_maintenance_update,
    parse_runtime_status,
    parse_submit_request,
)
from .pdf import (
    PdfDetectResult,
    PdfDocumentMirror,
    PdfModelDiff,
    PdfMutationResult,
    PdfOpenResult,
    PdfPageInfoMirror,
    PdfProgressEvent,
    PdfProgressPhase,
    PdfSaveResult,
    TextBlockMirror,
    TextLayerInfoMirror,
)

SCHEMA_VERSION = 2
"""Wire schema major version for the v2 protocol."""

__all__ = [
    "OCR_RESULT_PAYLOAD_TYPE",
    "SCHEMA_VERSION",
    "TERMINAL_ITEM_STATES",
    "TERMINAL_JOB_STATES",
    "CancelMode",
    "ContractError",
    "ErrorCategories",
    "ErrorCode",
    "ErrorPayload",
    "EvictionReason",
    "ItemOutcome",
    "ItemState",
    "JobCommand",
    "JobCommandKind",
    "JobItem",
    "JobKind",
    "JobPriority",
    "JobRef",
    "JobSnapshot",
    "JobState",
    "JobStateTransitionError",
    "JobSummary",
    "JobUpdate",
    "OcrResultV1",
    "OcrTextBlockV1",
    "PipelineSelection",
    "PipelineSpec",
    "PdfDetectResult",
    "PdfDocumentMirror",
    "PdfModelDiff",
    "PdfMutationResult",
    "PdfOpenResult",
    "PdfPageInfoMirror",
    "PdfProgressEvent",
    "PdfProgressPhase",
    "PdfSaveResult",
    "ProgressSnapshot",
    "ProgressUnit",
    "RecognitionResourceKind",
    "ResidencyEntry",
    "ResidencyKind",
    "ResidencyStatus",
    "ResultEntry",
    "RuntimeAccelerator",
    "RuntimeComponentActualState",
    "RuntimeComponentDesiredState",
    "RuntimeComponentState",
    "RuntimeComponentStatus",
    "RuntimeDriftReason",
    "RuntimeMaintenanceOperation",
    "RuntimeMaintenanceCommand",
    "RuntimeMaintenanceCommandKind",
    "RuntimeMaintenanceEvent",
    "RuntimeMaintenanceEventType",
    "RuntimeMaintenancePhase",
    "RuntimeMaintenanceReceipt",
    "RuntimeMaintenanceRequest",
    "RuntimeMaintenanceStatus",
    "RuntimeMaintenanceUpdate",
    "RuntimeOperationState",
    "RuntimeProfileStatus",
    "RuntimeServiceState",
    "RuntimeSourceIdentity",
    "RuntimeStatusSnapshot",
    "SchemaValidator",
    "SettingsSnapshot",
    "StageEvent",
    "SubmitItem",
    "SubmitRequest",
    "TextBlockMirror",
    "TextLayerInfoMirror",
    "UnknownJobError",
    "assert_item_transition",
    "assert_job_transition",
    "error_registry",
    "is_terminal_item",
    "is_terminal_job",
    "load_error_registry",
    "new_job_id",
    "parse_error_payload",
    "parse_job_command",
    "parse_job_ref",
    "parse_job_snapshot",
    "parse_job_update",
    "parse_ocr_result_payload",
    "parse_pipeline_selection",
    "parse_pipeline_spec",
    "parse_residency_entry",
    "parse_runtime_maintenance_event",
    "parse_runtime_maintenance_receipt",
    "parse_runtime_maintenance_update",
    "parse_runtime_status",
    "parse_submit_request",
]
