"""Deterministically generate small Protocol v2 capability/bootstrap bindings.

The formal OpenAPI document remains the source for operations; the two JSON
assets are deliberately tiny, generated language bindings suitable for the
future Protocol Python and NuGet packages.  ``--check`` is CI-safe: it writes
nothing and fails when checked-in generated files differ.
"""

from __future__ import annotations

import argparse
import json
import keyword
import re
from pathlib import Path
from pprint import pformat

ROOT = Path(__file__).resolve().parents[1]
V2 = ROOT / "packages/vibeocr-contracts-py/src/vibeocr/runtime_contracts"


def _read(name: str) -> dict:
    return json.loads((V2 / name).read_text(encoding="utf-8"))


def _python(capabilities: list[str], bootstrap: dict) -> str:
    names = [item.upper().replace(".", "_") for item in capabilities]
    constants = "\n".join(
        f'{name} = "{value}"' for name, value in zip(names, capabilities, strict=True)
    )
    values = ",\n    ".join(repr(item) for item in capabilities)
    return f"""# Generated by scripts/generate_runtime_protocol.py; DO NOT EDIT.\nfrom __future__ import annotations\n\n{constants}\n\nALL_CAPABILITIES: tuple[str, ...] = (\n    {values},\n)\nREADY_ENVELOPE_VERSION = {bootstrap["properties"]["ready_version"]["const"]}\nPROTOCOL_VERSION = {bootstrap["properties"]["protocol_version"]["const"]}\nSCHEMA_VERSION = {bootstrap["properties"]["schema_version"]["const"]}\n"""


def _operation_rows(openapi: dict) -> list[tuple[str, str, str]]:
    methods = {"get", "put", "post", "delete", "patch", "head", "options", "trace"}
    return sorted(
        (
            method.upper(),
            path,
            operation["operationId"],
        )
        for path, path_item in openapi["paths"].items()
        for method, operation in path_item.items()
        if method in methods
    )


def _csharp(
    capabilities: list[str],
    bootstrap: dict,
    errors: dict,
    openapi: dict,
) -> str:
    fields = "\n".join(
        f'    public const string {item.upper().replace(".", "_")} = "{item}";'
        for item in capabilities
    )
    ready = bootstrap["properties"]["ready_version"]["const"]
    protocol = bootstrap["properties"]["protocol_version"]["const"]
    schema = bootstrap["properties"]["schema_version"]["const"]
    capability_values = ",\n        ".join(
        f'"{capability}"' for capability in capabilities
    )
    operation_values = ",\n        ".join(
        f'new("{method}", "{path}", "{operation_id}")'
        for method, path, operation_id in _operation_rows(openapi)
    )
    operation_paths = "\n".join(
        f'    public const string {_pascal(operation_id)} = "{path}";'
        for _method, path, operation_id in _operation_rows(openapi)
    )
    error_values = ",\n    ".join(entry["code"] for entry in errors["codes"])
    return f"""// Generated by scripts/generate_runtime_protocol.py; DO NOT EDIT.
using System.Text.Json.Serialization;

namespace VibeOCR.Runtime.Contracts.Generated;

public static class RuntimeProtocol
{{
{fields}
    public const int ReadyEnvelopeVersion = {ready};
    public const int ProtocolVersion = {protocol};
    public const int SchemaVersion = {schema};
    public static IReadOnlySet<string> AllCapabilities {{ get; }} =
        new HashSet<string>(StringComparer.Ordinal)
        {{
        {capability_values}
        }};
    public static IReadOnlyList<RuntimeOperation> Operations {{ get; }} =
        new RuntimeOperation[]
        {{
        {operation_values}
        }};
}}

public readonly record struct RuntimeOperation(string Method, string Path, string OperationId);

public static class RuntimeOperationPaths
{{
{operation_paths}
}}

public enum RuntimeErrorCode
{{
    {error_values}
}}

public sealed record RuntimeReadyEnvelope(
    [property: JsonPropertyName("ready")] bool Ready,
    [property: JsonPropertyName("pid")] int Pid,
    [property: JsonPropertyName("port")] int Port,
    [property: JsonPropertyName("instance_id")] string InstanceId,
    [property: JsonPropertyName("protocol_version")] int ProtocolVersion,
    [property: JsonPropertyName("schema_version")] int SchemaVersion,
    [property: JsonPropertyName("ready_version")] int ReadyVersion,
    [property: JsonPropertyName("capabilities")] IReadOnlyList<string> Capabilities);

public sealed record RuntimeHealthEnvelope(
    [property: JsonPropertyName("schema_version")] int SchemaVersion,
    [property: JsonPropertyName("instance_id")] string InstanceId,
    [property: JsonPropertyName("protocol_version")] int ProtocolVersion,
    [property: JsonPropertyName("ready")] bool Ready,
    [property: JsonPropertyName("draining")] bool Draining,
    [property: JsonPropertyName("capabilities")] IReadOnlyList<string> Capabilities);
"""


def _python_operations(openapi: dict) -> str:
    rows = _operation_rows(openapi)
    entries = "\n".join(
        f'    ("{method}", "{path}"): "{operation_id}",'
        for method, path, operation_id in rows
    )
    values = ",\n    ".join(
        f'RuntimeOperation("{method}", "{path}", "{operation_id}")'
        for method, path, operation_id in rows
    )
    return f"""# Generated by scripts/generate_runtime_protocol.py; DO NOT EDIT.
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class RuntimeOperation:
    method: str
    path: str
    operation_id: str


OPERATION_IDS: dict[tuple[str, str], str] = {{
{entries}
}}
OPERATIONS: tuple[RuntimeOperation, ...] = (
    {values},
)
OPERATION_IDS_BY_NAME: dict[str, RuntimeOperation] = {{
    operation.operation_id: operation for operation in OPERATIONS
}}


def operation_path(operation_id: str) -> str:
    return OPERATION_IDS_BY_NAME[operation_id].path
"""


def _python_errors(errors: dict) -> str:
    enum_values = "\n".join(
        f'    {entry["code"]} = "{entry["code"]}"' for entry in errors["codes"]
    )
    entries = ",\n    ".join(
        (
            f"RuntimeErrorDefinition(RuntimeErrorCode.{entry['code']}, "
            f"{entry['category']!r}, {entry['http_status']}, "
            f"{entry['retryable']!r}, {entry['message']!r})"
        )
        for entry in errors["codes"]
    )
    return f"""# Generated by scripts/generate_runtime_protocol.py; DO NOT EDIT.
from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum


class RuntimeErrorCode(StrEnum):
{enum_values}


@dataclass(frozen=True, slots=True)
class RuntimeErrorDefinition:
    code: RuntimeErrorCode
    category: str
    http_status: int
    retryable: bool
    message: str


ERROR_DEFINITIONS: tuple[RuntimeErrorDefinition, ...] = (
    {entries},
)
ERROR_REGISTRY: dict[RuntimeErrorCode, RuntimeErrorDefinition] = {{
    definition.code: definition for definition in ERROR_DEFINITIONS
}}
"""


def _python_server_contracts(openapi: dict) -> str:
    contracts: dict[tuple[str, str], dict] = {}
    request_schemas: dict[str, dict] = {}
    response_schemas: dict[str, dict] = {}
    for method, path, operation_id in _operation_rows(openapi):
        operation = openapi["paths"][path][method.lower()]
        contract = {
            key: operation[key]
            for key in ("requestBody", "security")
            if key in operation
        }
        responses = {
            status: response
            for status, response in operation["responses"].items()
            if status != "200" or "application/json" not in response.get("content", {})
        }
        if responses:
            contract["responses"] = responses
        contracts[(method, path)] = contract
        request_body = operation.get("requestBody", {})
        json_content = request_body.get("content", {}).get("application/json", {})
        json_schema = json_content.get("schema")
        if json_schema is not None:
            if "$ref" not in json_schema:
                raise ValueError(
                    f"{method} {path} JSON request schema must be a named $ref"
                )
            schema_name = json_schema["$ref"].rsplit("/", 1)[-1]
            request_schemas[schema_name] = _resolve_local_refs(json_schema, openapi)
        success = operation["responses"].get("200", {})
        success_schema = (
            success.get("content", {}).get("application/json", {}).get("schema")
        )
        if success_schema is not None:
            response_schemas[operation_id] = _resolve_local_refs(
                success_schema,
                openapi,
            )
    return (
        "# Generated by scripts/generate_runtime_protocol.py; DO NOT EDIT.\n"
        "from __future__ import annotations\n\n"
        "from typing import Any\n\n"
        f"REQUEST_JSON_SCHEMAS: dict[str, dict[str, Any]] = {pformat(request_schemas, width=100, sort_dicts=True)}\n\n"
        f"RESPONSE_JSON_SCHEMAS: dict[str, dict[str, Any]] = {pformat(response_schemas, width=100, sort_dicts=True)}\n\n"
        f"ROUTE_CONTRACTS: dict[tuple[str, str], dict[str, Any]] = {pformat(contracts, width=100, sort_dicts=True)}\n"
    )


def _resolve_local_refs(
    value: object, root: dict, stack: tuple[str, ...] = ()
) -> object:
    """Dereference local OpenAPI refs into standalone JSON Schemas."""
    if isinstance(value, list):
        return [_resolve_local_refs(item, root, stack) for item in value]
    if not isinstance(value, dict):
        return value
    ref = value.get("$ref")
    if ref is None:
        return {
            key: _resolve_local_refs(item, root, stack) for key, item in value.items()
        }
    if not isinstance(ref, str) or not ref.startswith("#/"):
        raise ValueError(f"only local OpenAPI refs are supported: {ref!r}")
    if ref in stack:
        raise ValueError(f"recursive OpenAPI request schema is unsupported: {ref}")
    target: object = root
    for token in ref[2:].split("/"):
        if not isinstance(target, dict):
            raise ValueError(f"invalid OpenAPI ref: {ref}")
        target = target[token.replace("~1", "/").replace("~0", "~")]
    resolved = _resolve_local_refs(target, root, (*stack, ref))
    if not isinstance(resolved, dict):
        raise ValueError(f"OpenAPI ref must resolve to an object schema: {ref}")
    siblings = {
        key: _resolve_local_refs(item, root, stack)
        for key, item in value.items()
        if key != "$ref"
    }
    return {**resolved, **siblings}


def _python_type(schema: dict) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    choices = schema.get("oneOf") or schema.get("anyOf")
    if choices:
        types = list(dict.fromkeys(_python_type(choice) for choice in choices))
        return " | ".join(types)
    raw_type = schema.get("type")
    if isinstance(raw_type, list):
        return " | ".join(
            {
                "null": "None",
                "string": "str",
                "integer": "int",
                "number": "float",
                "boolean": "bool",
                "object": "dict[str, Any]",
                "array": "list[Any]",
            }.get(item, "Any")
            for item in raw_type
        )
    if "enum" in schema:
        return f"Literal[{', '.join(repr(value) for value in schema['enum'])}]"
    if "const" in schema:
        return f"Literal[{schema['const']!r}]"
    if raw_type == "array":
        return f"list[{_python_type(schema.get('items', {}))}]"
    return {
        "string": "str",
        "integer": "int",
        "number": "float",
        "boolean": "bool",
        "null": "None",
        "object": "dict[str, Any]",
    }.get(raw_type, "Any")


def _python_wire_types(openapi: dict) -> str:
    aliases: list[str] = []
    classes: list[str] = []
    for name, schema in sorted(openapi["components"]["schemas"].items()):
        properties = schema.get("properties")
        if not isinstance(properties, dict):
            if "enum" in schema:
                aliases.append(f"{name} = {_python_type(schema)}")
            continue
        required = set(schema.get("required", []))
        fields: list[str] = []
        for field, field_schema in properties.items():
            safe_field = f"{field}_" if keyword.iskeyword(field) else field
            wrapper = "Required" if field in required else "NotRequired"
            fields.append(f"    {safe_field}: {wrapper}[{_python_type(field_schema)}]")
        body = "\n".join(fields) or "    pass"
        classes.append(f"class {name}(TypedDict, total=False):\n{body}")
    return (
        "# Generated by scripts/generate_runtime_protocol.py; DO NOT EDIT.\n"
        "from __future__ import annotations\n\n"
        "from typing import Any, Literal, NotRequired, Required, TypedDict\n\n"
        + "\n".join(aliases)
        + ("\n\n\n" if aliases else "\n")
        + "\n\n\n".join(classes)
        + "\n"
    )


def _pascal(value: str) -> str:
    return "".join(
        part[:1].upper() + part[1:]
        for part in re.split(r"[^A-Za-z0-9]+", value)
        if part
    )


def _csharp_literal_type(values: list[object]) -> str:
    kinds = {
        "bool"
        if isinstance(value, bool)
        else "int"
        if isinstance(value, int)
        else "double"
        if isinstance(value, float)
        else "string"
        if isinstance(value, str)
        else "unknown"
        for value in values
        if value is not None
    }
    if kinds <= {"int", "double"} and kinds:
        return "double" if "double" in kinds else "int"
    if len(kinds) == 1:
        return next(iter(kinds))
    return "JsonElement"


def _csharp_allows_null(schema: dict) -> bool:
    raw_type = schema.get("type")
    if isinstance(raw_type, list) and "null" in raw_type:
        return True
    choices = schema.get("oneOf") or schema.get("anyOf") or []
    return any(choice.get("type") == "null" for choice in choices)


def _csharp_type(schema: dict) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "const" in schema:
        return _csharp_literal_type([schema["const"]])
    if "enum" in schema:
        return _csharp_literal_type(schema["enum"])
    choices = schema.get("oneOf") or schema.get("anyOf")
    if choices:
        non_null = [choice for choice in choices if choice.get("type") != "null"]
        if len(non_null) == 1:
            return _csharp_type(non_null[0])
        return "JsonElement"
    raw_type = schema.get("type")
    if isinstance(raw_type, list):
        non_null = [item for item in raw_type if item != "null"]
        if len(non_null) == 1:
            return _csharp_type({**schema, "type": non_null[0]})
        return "JsonElement"
    if raw_type == "array":
        return f"IReadOnlyList<{_csharp_type(schema.get('items', {}))}>"
    return {
        "string": "string",
        "integer": "int",
        "number": "double",
        "boolean": "bool",
        "object": "IReadOnlyDictionary<string, JsonElement>",
    }.get(raw_type, "JsonElement")


def _csharp_wire_types(openapi: dict) -> str:
    enums: list[str] = []
    classes: list[str] = []
    for name, schema in sorted(openapi["components"]["schemas"].items()):
        properties = schema.get("properties")
        if not isinstance(properties, dict):
            if "enum" in schema:
                members = ",\n".join(
                    f'    [JsonStringEnumMemberName("{value}")]\n'
                    f"    {_pascal(str(value))}"
                    for value in schema["enum"]
                    if value is not None
                )
                enums.append(
                    f"[JsonConverter(typeof({name}JsonConverter))]\n"
                    f"public enum {name}\n{{\n{members}\n}}\n\n"
                    f"public sealed class {name}JsonConverter "
                    f": JsonStringEnumConverter<{name}>\n"
                    "{\n"
                    f"    public {name}JsonConverter()\n"
                    "        : base(namingPolicy: null, allowIntegerValues: false)\n"
                    "    {\n"
                    "    }\n"
                    "}"
                )
            continue
        required = set(schema.get("required", []))
        fields: list[str] = []
        for field, field_schema in properties.items():
            field_type = _csharp_type(field_schema)
            property_name = _pascal(field)
            is_required = field in required
            modifier = "required " if is_required else ""
            suffix = (
                "?"
                if (_csharp_allows_null(field_schema) or not is_required)
                and not field_type.endswith("?")
                else ""
            )
            fields.append(
                f'    [JsonPropertyName("{field}")]\n'
                f"    public {modifier}{field_type}{suffix} {property_name} {{ get; init; }}"
            )
        classes.append(
            f"public sealed record {name}\n{{\n" + "\n\n".join(fields) + "\n}"
        )
    return (
        "// Generated by scripts/generate_runtime_protocol.py; DO NOT EDIT.\n"
        "#nullable enable\n"
        "using System.Text.Json;\n"
        "using System.Text.Json.Serialization;\n\n"
        "namespace VibeOCR.Runtime.Contracts.Generated.Wire;\n\n"
        + "\n\n".join(enums)
        + ("\n\n" if enums else "")
        + "\n\n".join(classes)
        + "\n"
    )


def _python_models(bootstrap: dict) -> str:
    required = tuple(bootstrap["required"])
    return f"""# Generated by scripts/generate_runtime_protocol.py; DO NOT EDIT.
from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Any

_READY_KEYS = frozenset({required!r})
_HEALTH_KEYS = frozenset({{
    "schema_version",
    "instance_id",
    "protocol_version",
    "ready",
    "draining",
    "capabilities",
}})


def _required_object(payload: Any, keys: frozenset[str], name: str) -> dict[str, Any]:
    if not isinstance(payload, dict) or not keys.issubset(payload):
        raise ValueError(f"{{name}} is missing required Protocol v2 fields")
    return payload


def _integer(value: Any, field: str) -> int:
    if type(value) is not int:
        raise ValueError(f"{{field}} must be an integer")
    return value


def _boolean(value: Any, field: str) -> bool:
    if type(value) is not bool:
        raise ValueError(f"{{field}} must be a boolean")
    return value


def _string(value: Any, field: str) -> str:
    if not isinstance(value, str) or not value:
        raise ValueError(f"{{field}} must be a non-empty string")
    return value


def _capabilities(value: Any) -> tuple[str, ...]:
    if not isinstance(value, list) or any(not isinstance(item, str) for item in value):
        raise ValueError("capabilities must be a string array")
    result = tuple(value)
    if len(result) != len(set(result)):
        raise ValueError("capabilities contain duplicates")
    return result


@dataclass(frozen=True, slots=True)
class RuntimeReadyEnvelope:
    ready: bool
    pid: int
    port: int
    instance_id: str
    protocol_version: int
    schema_version: int
    capabilities: tuple[str, ...]
    ready_version: int

    @classmethod
    def from_payload(cls, payload: Any) -> RuntimeReadyEnvelope:
        data = _required_object(payload, _READY_KEYS, "ready envelope")
        return cls(
            ready=_boolean(data["ready"], "ready"),
            pid=_integer(data["pid"], "pid"),
            port=_integer(data["port"], "port"),
            instance_id=_string(data["instance_id"], "instance_id"),
            protocol_version=_integer(data["protocol_version"], "protocol_version"),
            schema_version=_integer(data["schema_version"], "schema_version"),
            capabilities=_capabilities(data["capabilities"]),
            ready_version=_integer(data["ready_version"], "ready_version"),
        )


@dataclass(frozen=True, slots=True)
class RuntimeHealthEnvelope:
    schema_version: int
    instance_id: str
    protocol_version: int
    ready: bool
    draining: bool
    capabilities: tuple[str, ...]

    @classmethod
    def from_payload(cls, payload: Any) -> RuntimeHealthEnvelope:
        data = _required_object(payload, _HEALTH_KEYS, "health envelope")
        return cls(
            schema_version=_integer(data["schema_version"], "schema_version"),
            instance_id=_string(data["instance_id"], "instance_id"),
            protocol_version=_integer(data["protocol_version"], "protocol_version"),
            ready=_boolean(data["ready"], "ready"),
            draining=_boolean(data["draining"], "draining"),
            capabilities=_capabilities(data["capabilities"]),
        )

    def to_payload(self) -> dict[str, Any]:
        payload = asdict(self)
        payload["capabilities"] = list(self.capabilities)
        return payload
"""


def _generated_init() -> str:
    return '''"""Generated Protocol v2 bindings; regenerate instead of editing."""

from .capabilities import (
    ALL_CAPABILITIES,
    PROTOCOL_VERSION,
    READY_ENVELOPE_VERSION,
    SCHEMA_VERSION,
)
from .error_codes import ERROR_DEFINITIONS, ERROR_REGISTRY, RuntimeErrorCode
from .models import RuntimeHealthEnvelope, RuntimeReadyEnvelope
from .operations import (
    OPERATION_IDS,
    OPERATION_IDS_BY_NAME,
    OPERATIONS,
    RuntimeOperation,
    operation_path,
)
from .server import REQUEST_JSON_SCHEMAS, RESPONSE_JSON_SCHEMAS, ROUTE_CONTRACTS

__all__ = [
    "ALL_CAPABILITIES",
    "ERROR_DEFINITIONS",
    "ERROR_REGISTRY",
    "OPERATIONS",
    "OPERATION_IDS",
    "OPERATION_IDS_BY_NAME",
    "PROTOCOL_VERSION",
    "READY_ENVELOPE_VERSION",
    "REQUEST_JSON_SCHEMAS",
    "RESPONSE_JSON_SCHEMAS",
    "ROUTE_CONTRACTS",
    "SCHEMA_VERSION",
    "RuntimeErrorCode",
    "RuntimeHealthEnvelope",
    "RuntimeOperation",
    "RuntimeReadyEnvelope",
    "operation_path",
]
'''


def _standalone_error_schema(openapi: dict) -> str:
    schema = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://vibeocr/protocol/v2/errors.schema.json",
        "title": "VibeOCR v2 Error Response",
        **openapi["components"]["schemas"]["Error"],
    }
    return json.dumps(schema, indent=2, ensure_ascii=False) + "\n"


def _outputs() -> dict[Path, str]:
    capabilities = _read("capabilities.json")["capabilities"]
    bootstrap = _read("bootstrap.schema.json")
    errors = _read("errors.json")
    openapi = _read("openapi.yaml")
    return {
        V2 / "schemas/errors.schema.json": _standalone_error_schema(openapi),
        V2 / "generated/capabilities.py": _python(capabilities, bootstrap),
        V2 / "generated/operations.py": _python_operations(openapi),
        V2 / "generated/error_codes.py": _python_errors(errors),
        V2 / "generated/models.py": _python_models(bootstrap),
        V2 / "generated/server.py": _python_server_contracts(openapi),
        V2 / "generated/wire_types.py": _python_wire_types(openapi),
        V2 / "generated/__init__.py": _generated_init(),
        V2 / "generated/RuntimeProtocol.g.cs": _csharp(
            capabilities,
            bootstrap,
            errors,
            openapi,
        ),
        V2 / "generated/RuntimeWireTypes.g.cs": _csharp_wire_types(openapi),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale: list[Path] = []
    for path, content in _outputs().items():
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            stale.append(path)
            if not args.check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8", newline="\n")
    if stale and args.check:
        print("Generated runtime protocol files are stale:")
        print("\n".join(str(path.relative_to(ROOT)) for path in stale))
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
